kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policy-validator
rules:
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "persistentvolumes"
  verbs:
  - "get"
  - "list"
  - "watch"
