apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: messagequeues.core.dsc
spec:
  group: core.dsc
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              brokers:
                type: array
                items:
                  type: string
              saslRef:
                type: object
                properties:
                  namespace:
                    type: string
                  name:
                    type: string
  names:
    kind: MessageQueue
    singular: messagequeue
    plural: messagequeues
  scope: Namespaced
