apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rdbdatas.core.dsc
spec:
  group: core.dsc
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              url:
                type: string
              authenticationRef:
                type: object
                properties:
                  namespace:
                    type: string
                  name:
                    type: string
  names:
    kind: RdbData
    singular: rdbdata
    plural: rdbdatas
  scope: Namespaced
