kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: provider-lifetime-controller-0
rules:
- apiGroups:
  - "lifetimes.dsc"
  resources:
  - "datalifetimes"
  verbs:
  - "*"
