kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: provider-lifetime-controller-0
subjects:
- kind: ServiceAccount
  namespace: default
  name: lifetime-controller-0
roleRef:
  kind: ClusterRole
  name: provider-lifetime-controller-0
  apiGroup: rbac.authorization.k8s.io
