kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: provider-lifetime-controller-1
rules:
- apiGroups:
  - "lifetimes.dsc"
  resources:
  - "datalifetimes"
  verbs:
  - "*"
- apiGroups:
  - "core.dsc"
  resources:
  - "messagequeues"
  resourceNames:
  - "sample-message-queue-1"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - "secrets"
  resourceNames:
  - "message-queue-secret-1"
  verbs:
  - "get"
  - "list"
  - "watch"
