/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	corev1alpha1 "github.com/FujitsuResearch/data-sharing-controllers-on-k8s/pkg/apis/cr/core/v1alpha1"
	versioned "github.com/FujitsuResearch/data-sharing-controllers-on-k8s/pkg/client/cr/core/clientset/versioned"
	internalinterfaces "github.com/FujitsuResearch/data-sharing-controllers-on-k8s/pkg/client/cr/core/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/FujitsuResearch/data-sharing-controllers-on-k8s/pkg/client/cr/core/listers/core/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RdbDataInformer provides access to a shared informer and lister for
// RdbDatas.
type RdbDataInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RdbDataLister
}

type rdbDataInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRdbDataInformer constructs a new informer for RdbData type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRdbDataInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRdbDataInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRdbDataInformer constructs a new informer for RdbData type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRdbDataInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().RdbDatas(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().RdbDatas(namespace).Watch(context.TODO(), options)
			},
		},
		&corev1alpha1.RdbData{},
		resyncPeriod,
		indexers,
	)
}

func (f *rdbDataInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRdbDataInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rdbDataInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&corev1alpha1.RdbData{}, f.defaultInformer)
}

func (f *rdbDataInformer) Lister() v1alpha1.RdbDataLister {
	return v1alpha1.NewRdbDataLister(f.Informer().GetIndexer())
}
