apiVersion: core.dsc/v1alpha1
kind: MessageQueue
metadata:
  name: sample-message-queue-1
spec:
  brokers: # broker addresses, e.g. "127.0.0.1:9092"
  -
  saslRef:
    namespace: default
    name: message-queue-secret-1
