kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-controller
subjects:
- kind: ServiceAccount
  namespace: dsc
  name: volume-controller
roleRef:
  kind: ClusterRole
  name: volume-controller
  apiGroup: rbac.authorization.k8s.io
