kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dsc
  name: volume-controller
rules:
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "persistentvolumes"
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
